adding huggingface inference support + litellm debugger
Codium-ai/pr-agent pull request #228
Opened 2023-08-21 22:35 UTC by krrishdholakia

Hi @mrT23 @okotek,

Following up on @dzlab's request and adding Huggingface Inference support (we also support palm - via vertex ai, together_ai + baseten deployments, can add those too). 

We also introduced a free debugging tool - added instructions on how to use that in the INSTALL.MD docs. Let me know if another place might work better - https://docs.litellm.ai/docs/debugging/hosted_debugging. 

Can add additional docs + testing if the initial PR looks good.

2023-08-22 06:03 UTC, mrT23 commented
Thanks a lot @krrishdholakia,

Can you elaborate a bit more on what it means to support "HUGGINGFACE" ?
do you have an easy example to demonstrate the usage of a HUGGINGFACE model ?

2023-08-22 09:11 UTC, dzlab commented on pr_agent/algo/ai_handler.py
> +                litellm.huggingface_key = get_settings().huggingface.key
this looks like duplication, no?

2023-08-22 10:26 UTC, dzlab commented
@krrishdholakia how does this debugger tool compares to [langsmith](https://docs.smith.langchain.com/)?

2023-08-22 12:55 UTC, krrishdholakia commented
@dzlab haven't tried langsmith out - it looks great! I just needed a way to tell if the raw api calls were being made. 

@mrT23 It works with the HF Inference API - https://docs.litellm.ai/docs/completion/supported#hugging-face-inference-api

We also support deployment providers like Baseten, TogetherAI. 

I believe Baseten has a deployment of WizardLM you can use out of the box - https://docs.litellm.ai/docs/completion/supported#baseten-models

2023-08-22 13:33 UTC, mrT23 approved these changes

2023-08-22 13:35 UTC, mrT23 commented
ok. i will merge and try the example you sent :)

HF Inference API is indeed a popular service

2023-08-22 13:42 UTC, mrT23 commented
Preparing review...

2023-08-22 13:43 UTC, mrT23 commented on requirements.txt
> +litellm~=0.1.445
**Suggestion:** The 'litellm' package is listed twice with different versions. Please ensure to keep only the required version.
```suggestion
litellm~=0.1.445
```

2023-08-22 13:43 UTC, mrT23 commented on pr_agent/algo/ai_handler.py
> +                litellm.huggingface_key = get_settings().huggingface.key
**Suggestion:** There seems to be a duplication of code for setting the 'replicate_key' and 'huggingface_key'. Please ensure that each key is set only once.
```suggestion
            if get_settings().get('REPLICATE.KEY', None):
                litellm.replicate_key = get_settings().replicate.key
            if get_settings().get('HUGGINGFACE.KEY', None):
                litellm.huggingface_key = get_settings().huggingface.key
```

2023-08-22 13:45 UTC, mrT23 commented on pr_agent/algo/ai_handler.py
> +                litellm.huggingface_key = get_settings().huggingface.key
@dzlab  "/improve" agrees with you :-)

2023-08-22 14:48 UTC, okotek requested changes

2023-08-22 14:48 UTC, okotek commented on requirements.txt
> +litellm~=0.1.445
Please also change in pyproject.toml

2023-08-23 06:16 UTC, mrT23 approved these changes

2023-08-23 06:17 UTC, merged

2023-08-23 06:36 UTC, mrT23 commented
i fixed the minor issues in another commit

2023-08-24 04:40 UTC, krrishdholakia commented
Thanks! @mrT23