update the pr-agent name to title case
Codium-ai/pr-agent pull request #31
Opened 2023-07-10 18:10 UTC by tombrewsviews

A question related to the naming convention consistency - do we want to keep the dash/hyphen in the name?

Right now, I updated to PR-Agent, but we list tools like PR Review and PR Q&A without the dashes. @almog-lv @GadiZimerman @coditamar

2023-07-11 12:40 UTC, okotek commented
PR-Agent without a dash doesn't work well, too similar to "pregnant". 
Codium-ai is the org name in GitHub, it's consistent with other orgs styling.
pr-agent in small letters is the project name. It's common for these project to be in small letters.

@tombrewsviews

2023-07-11 12:45 UTC, mrT23 commented
i also think it should be in capitals
"PR-Agent"

pr-agent is just wierd. 99.9% of opensource projects are not named with lowercase

2023-07-11 14:01 UTC, okotek commented
https://github.com/tensorflow/tensorflow
https://github.com/pytorch/pytorch
https://github.com/mongodb/mongo
https://github.com/mysql/mysql-server
https://github.com/facebook/react

While I don't mind that the styling in the docs will be capitalized, I was referring to the GitHub slug which should be lower case (as it is today)

2023-07-11 14:06 UTC, okotek requested changes

2023-07-11 14:06 UTC, okotek commented on README.md
> +[![GitHub license](https://img.shields.io/badge/License-Apache_2.0-blue.svg)](https://github.com/Codium-ai/PR-Agent/blob/main/LICENSE)
```suggestion
[![GitHub license](https://img.shields.io/badge/License-Apache_2.0-blue.svg)](https://github.com/Codium-ai/pr-agent/blob/main/LICENSE)
```

2023-07-11 14:06 UTC, okotek commented on README.md
> +docker run --rm -it -e OPENAI.KEY=<your key> -e GITHUB.USER_TOKEN=<your token> codiumai/PR-Agent --pr_url <pr url>
```suggestion
docker run --rm -it -e OPENAI.KEY=<your key> -e GITHUB.USER_TOKEN=<your token> codiumai/pr-agent --pr_url <pr url>
```

2023-07-11 14:06 UTC, okotek commented on README.md
> +docker run --rm -it -e OPENAI.KEY=<your key> -e GITHUB.USER_TOKEN=<your token> codiumai/PR-Agent --pr_url <pr url> --question "<your question>"
```suggestion
docker run --rm -it -e OPENAI.KEY=<your key> -e GITHUB.USER_TOKEN=<your token> codiumai/pr-agent --pr_url <pr url> --question "<your question>"
```

2023-07-11 14:06 UTC, okotek commented on README.md
> +git clone https://github.com/codium-ai/pr-agent.git
```suggestion
git clone https://github.com/Codium-ai/pr-agent.git
```

2023-07-11 14:06 UTC, okotek commented on README.md
> +git clone https://github.com/codium-ai/pr-agent.git
```suggestion
git clone https://github.com/Codium-ai/pr-agent.git
```

2023-07-11 14:06 UTC, okotek commented on README.md
> +docker build . -t codiumai/PR-Agent:github_app --target github_app -f docker/Dockerfile
```suggestion
docker build . -t codiumai/pr-agent:github_app --target github_app -f docker/Dockerfile
```

2023-07-11 14:06 UTC, okotek commented on README.md
> +docker push codiumai/PR-Agent:github_app  # Push to your Docker repository
```suggestion
docker push codiumai/pr-agent:github_app  # Push to your Docker repository
```

2023-07-13 06:55 UTC, zmeir commented
Preparing review...

2023-07-16 13:37 UTC, okotek requested changes

2023-07-16 13:37 UTC, okotek commented on README.md
> +![Review generation process](./pics/PR-Agent-review-process1.gif)
```suggestion
![Review generation process](./pics/pr-agent-review-process1.gif)
```

2023-07-16 13:38 UTC, okotek approved these changes

2023-07-16 13:50 UTC, okotek approved these changes

2023-07-16 13:50 UTC, merged