Tr/agent logic
Codium-ai/pr-agent pull request #78
Opened 2023-07-17 12:50 UTC by mrT23

s

2023-07-17 14:22 UTC, BossModus666 reviewed
Marcelschween99@outlook.com

2023-07-17 14:30 UTC, BossModus666 approved these changes

2023-07-18 05:07 UTC, mrT23 commented
Preparing pr description...

2023-07-18 05:08 UTC, mrT23 commented
Preparing pr description...

2023-07-18 07:06 UTC, okotek requested changes

2023-07-18 07:06 UTC, okotek commented on pr_agent/agent/pr_agent.py
> +            if settings.pr_reviewer.ask_and_reflect or any(cmd in request for cmd in ["/reflect_and_review"]):
```suggestion
            if settings.pr_reviewer.ask_and_reflect or "/reflect_and_review" in request:
```

2023-07-18 07:06 UTC, okotek commented on pr_agent/servers/github_action_runner.py
> +                    if any(cmd in body for cmd in ["/answer"]):
let me replace that with PRAgent call

2023-07-18 07:06 UTC, okotek commented on pr_agent/tools/pr_reviewer.py
> +from pr_agent.git_providers import get_git_provider, GithubProvider
```suggestion
from pr_agent.git_providers import get_git_provider
```

2023-07-18 07:06 UTC, okotek commented on pr_agent/tools/pr_reviewer.py
> +        if self.is_answer and type(self.git_provider) != GithubProvider:
let me add is_supported in git provider

2023-07-18 07:36 UTC, okotek approved these changes

2023-07-18 07:36 UTC, okotek commented on pr_agent/tools/pr_reviewer.py
> +            discussion_messages = self.git_provider.pr.get_issue_comments()
Let me add that function in the base class

2023-07-18 07:37 UTC, merged

2023-07-18 08:17 UTC, okotek commented
/reflect_and_review

2023-07-18 08:18 UTC, okotek commented on pr_agent/tools/pr_reviewer.py
> +        if self.is_answer and not self.git_provider.is_supported("get_issue_comments"):
We should probably do that

2023-07-18 08:20 UTC, okotek commented
/answer 
1. These commands are also reflected in the command line interface.
2. It is handled in the Jinja template of the AI prompt.
3. If this setting is set, every review defaults to "reflect and review"